FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    latexmk \
    texlive-xetex \
    texlive-latex-recommended \
    texlive-latex-extra \
    texlive-plain-generic \
    texlive-fonts-recommended \
    fonts-texgyre \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /workdir
